### ISSUE TITLE
./hack/run-locally.sh isn't working

### ISSUE THREAD

**Issue by tssurya** [openshift/cluster-network-operator#1289]
```
I0121 20:47:27.951103 1943746 log.go:184] Controller "ConnectivityCheckController" resync interval is set to 0s which might lead to client request throttling
I0121 20:47:27.954195 1943746 base_controller.go:66] Waiting for caches to sync for ConnectivityCheckController
I0121 20:47:38.170078 1943746 trace.go:205] Trace[211140115]: "Reflector ListAndWatch" name:k8s.io/client-go@v0.22.1/tools/cache/reflector.go:167 (21-Jan-2022 20:47:27.956) (total time: 10213ms):
Trace[211140115]: ---"Objects listed" 10213ms (20:47:38.169)
Trace[211140115]: [10.213414132s] [10.213414132s] END
I0121 20:47:39.841632 1943746 trace.go:205] Trace[1136817626]: "Reflector ListAndWatch" name:k8s.io/client-go@v0.22.1/tools/cache/reflector.go:167 (21-Jan-2022 20:47:27.957) (total time: 11884ms):
Trace[1136817626]: ---"Objects listed" 11884ms (20:47:39.841)
Trace[1136817626]: [11.884121269s] [11.884121269s] END
I0121 20:47:39.842773 1943746 trace.go:205] Trace[1297844340]: "Reflector ListAndWatch" name:k8s.io/client-go@v0.22.1/tools/cache/reflector.go:167 (21-Jan-2022 20:47:27.955) (total time: 11887ms):
Trace[1297844340]: ---"Objects listed" 11887ms (20:47:39.842)
Trace[1297844340]: [11.887396601s] [11.887396601s] END
I0121 20:47:40.872985 1943746 trace.go:205] Trace[2118805739]: "Reflector ListAndWatch" name:k8s.io/client-go@v0.22.1/tools/cache/reflector.go:167 (21-Jan-2022 20:47:27.956) (total time: 12916ms):
Trace[2118805739]: ---"Objects listed" 12916ms (20:47:40.872)
Trace[2118805739]: [12.916855373s] [12.916855373s] END

F0121 20:49:27.950351 1943746 operator.go:93] Failed to start controller-runtime manager: failed to wait for pki-controller caches to sync: timed out waiting for cache to be synced
goroutine 470 [running]:
k8s.io/klog/v2.stacks(0x1)
	k8s.io/klog/v2@v2.9.0/klog.go:1026 +0x8a
k8s.io/klog/v2.(*loggingT).output(0x3bb4d40, 0x3, {0x0, 0x0}, 0xc00044cd90, 0x0, {0x2df7d5f, 0xb}, 0x0, 0x0)
	k8s.io/klog/v2@v2.9.0/klog.go:975 +0x63d
k8s.io/klog/v2.(*loggingT).printf(0x0, 0xaa17a0, {0x0, 0x0}, {0x0, 0x0}, {0x24245af, 0x2e}, {0xc0007f66c0, 0x1, ...})
	k8s.io/klog/v2@v2.9.0/klog.go:753 +0x1e5
k8s.io/klog/v2.Fatalf(...)
	k8s.io/klog/v2@v2.9.0/klog.go:1514
github.com/openshift/cluster-network-operator/pkg/operator.RunOperator.func2()
	github.com/openshift/cluster-network-operator/pkg/operator/operator.go:93 +0xd5
created by github.com/openshift/cluster-network-operator/pkg/operator.RunOperator
	github.com/openshift/cluster-network-operator/pkg/operator/operator.go:90 +0x585

```

**Comment by tssurya** [comment]
This cannot be reproduced now. Maybe this was a glitch. Closing this issue until we see it again.
